/* Learnova curriculum expansion: subject coverage and topic scaffolding aligned to NaCCA's published subject structure. */
(()=>{
 const C=window.LEARNOVA_CURRICULUM||{};
 const packs={
  'Primary 1':['Number and Counting','Addition and Subtraction','Shapes and Space','Measurement','Patterns','Time','Money','Data and Sorting','Living Things','Materials Around Us','My Body and Senses','Plants Around Us','Animals Around Us','Weather and Seasons','Keeping the Environment Clean'],
  'Primary 2':['Place Value','Multiplication and Division','Fractions','Length and Mass','Capacity','Time and Calendar','Money and Buying','2D and 3D Shapes','Plants and Their Needs','Animals and Habitats','Water and Air','Health and Hygiene','Weather','Our Community','Rules and Responsibilities'],
  'Primary 3':['Numbers to Thousands','Four Operations','Fractions and Decimals','Perimeter and Area','Angles and Lines','Money and Profit Basics','Measurement','Tables and Graphs','Matter and Its Uses','Forces and Movement','Energy in Daily Life','Human Health','Food and Nutrition','Environment and Conservation','Simple Machines'],
  'Primary 4':['Large Numbers and Place Value','Factors and Multiples','Fractions','Decimals','Ratio and Proportion','Angles and Geometry','Area and Perimeter','Measurement and Units','Data and Graphs','Algebraic Patterns','Matter','Forces and Energy','The Human Body','Plants and Reproduction','Environment and Resources'],
  'Primary 5':['Whole Numbers and Operations','Fractions and Mixed Numbers','Decimals and Percentages','Ratio and Proportion','Geometry','Area and Volume','Data Handling','Probability Basics','Energy','Electricity','Forces','Matter','Human Reproduction and Growth','Disease Prevention','Natural Resources'],
  'Primary 6':['Integers and Number Operations','Fractions Decimals and Percentages','Ratio Rate and Proportion','Algebraic Expressions','Equations','Geometry and Construction','Area Surface Area and Volume','Statistics','Probability','Financial Mathematics','Energy Transformation','Electricity and Magnetism','Human Body Systems','Ecosystems','Environmental Protection'],
  'JHS 1':['Integers and Rational Numbers','Fractions Decimals and Percentages','Algebraic Expressions','Linear Equations','Ratio Rate and Proportion','Geometry and Angles','Measurement','Statistics','Probability','Number Patterns','Scientific Measurement','Cells and Living Things','Matter','Forces','Energy','The Earth and Environment'],
  'JHS 2':['Indices and Standard Form','Algebraic Expressions','Linear Equations and Inequalities','Simultaneous Equations','Graphs','Pythagoras Theorem','Similarity and Congruence','Mensuration','Statistics','Probability','Chemical Changes','Atomic Structure','Energy','Electricity','Human Reproduction','Ecology'],
  'JHS 3':['Number Bases','Surds and Indices','Quadratic Expressions','Functions and Graphs','Variation','Trigonometry','Circle Geometry','Mensuration','Statistics and Probability','Financial Mathematics','Chemical Reactions','Waves','Electricity and Magnetism','Genetics and Heredity','Ecology and Conservation','Health and Disease'],
  'SHS 1':['Sets and Logic','Number Systems','Algebra','Functions','Coordinate Geometry','Trigonometry','Sequences and Series','Vectors','Statistics','Probability','Calculus Introduction','Scientific Measurement','Mechanics','Waves','Atomic Structure','Chemical Bonding','Cell Biology','Ecology','Grammar and Communication','Critical Thinking'],
  'SHS 2':['Advanced Algebra','Functions and Transformations','Logarithms and Exponentials','Trigonometry','Differentiation','Integration','Probability Distributions','Statistics','Mechanics','Electric Fields','Magnetic Fields','Organic Chemistry','Chemical Equilibrium','Genetics','Evolution','Economics of Ghana','Governance and Democracy','Research Skills'],
  'SHS 3':['Advanced Functions','Calculus Applications','Differential Equations Basics','Probability and Statistics','Financial Mathematics','Mathematical Modelling','Mechanics and Energy','Electricity and Electronics','Modern Physics','Organic Chemistry','Biochemistry','Genetics and Biotechnology','Ecology and Sustainability','Research and Data Analysis','Exam Problem Solving','Career and Tertiary Readiness']
 };
 const subjectTopics={
  'English Language':['Reading Comprehension','Vocabulary Development','Grammar','Parts of Speech','Sentence Structure','Punctuation','Writing','Summary Writing','Oral Communication','Literature and Text Analysis'],
  'Mathematics':['Number and Numeration','Algebra','Geometry','Measurement','Statistics','Probability','Graphs','Financial Mathematics','Problem Solving','Mathematical Reasoning'],
  'Core Mathematics':['Number and Numeration','Algebra','Geometry','Measurement','Statistics','Probability','Functions','Calculus','Vectors','Financial Mathematics'],
  'Advanced Mathematics':['Functions','Algebra','Trigonometry','Coordinate Geometry','Sequences and Series','Calculus','Vectors','Statistics','Probability','Mathematical Modelling'],
  'Additional Mathematics':['Functions','Algebra','Trigonometry','Coordinate Geometry','Sequences and Series','Calculus','Vectors','Statistics','Probability','Mathematical Modelling'],
  'Science':['Living Things','Matter','Energy','Forces','The Human Body','Plants','Animals','Earth and Space','Environment','Health and Safety'],
  'Integrated Science':['Scientific Method','Matter','Cells','Forces and Motion','Energy','Electricity','Waves','Human Biology','Ecology','Chemical Reactions'],
  'General Science':['Scientific Measurement','Matter and Atomic Structure','Mechanics','Waves','Electricity','Chemistry','Cell Biology','Genetics','Ecology','Scientific Investigation'],
  'Social Studies':['The Individual and Society','Family and Community','Culture','Governance','Citizenship','Ghanaian Economy','Resources','Environment','Population','National Development'],
  'History':['Sources of History','Early Ghanaian States','Trade and Migration','European Contact','Colonial Rule','Nationalism','Independence','Post-Independence Ghana','Ghanaian Heritage','Historical Thinking'],
  'Our World Our People':['Myself and My Family','My School','My Community','Our Environment','Culture and Identity','Citizenship','Health and Safety','Occupations','Resources','Ghana and the World'],
  'Religious and Moral Education':['God and Creation','Holy Books','Worship','Moral Values','Family Life','Community Responsibility','Peace and Conflict','Stewardship','Religious Practices','Respect and Tolerance'],
  'Religious and Moral Education (RME)':['God and Creation','Holy Books','Worship','Moral Values','Family Life','Community Responsibility','Peace and Conflict','Stewardship','Religious Practices','Respect and Tolerance'],
  'Physical Education':['Locomotor Skills','Non-Locomotor Skills','Manipulative Skills','Fitness','Games','Athletics','Dance','Safety','Healthy Living','Teamwork'],
  'Physical Education and Health':['Fitness and Wellness','Movement Skills','Games and Sports','Athletics','Dance','Personal Hygiene','Nutrition','Safety','Mental Wellbeing','Healthy Lifestyle'],
  'Creative Arts':['Drawing','Colour','Pattern','Design','Music','Drama','Dance','Craft','Art Appreciation','Creative Projects'],
  'Creative Arts and Design':['Design Process','Drawing and Illustration','Colour','Graphic Design','Craft','Textiles','Music','Drama','Dance','Creative Projects'],
  'Computing':['Computer Systems','Input and Output','Files and Folders','Word Processing','Presentations','Spreadsheets','Internet Safety','Algorithms','Programming','Digital Citizenship'],
  'French':['Greetings and Introductions','Numbers','Family','School','Colours','Days and Months','Food and Drinks','Directions','Everyday Conversations','Basic Grammar'],
  'Ghanaian Language':['Alphabet and Sounds','Greetings','Nouns','Pronouns','Verbs','Sentence Formation','Reading','Writing','Proverbs','Culture and Oral Tradition'],
  'Arabic':['Alphabet','Sounds and Pronunciation','Numbers','Greetings','Family','School Vocabulary','Basic Sentences','Reading','Writing','Everyday Communication'],
  'Career Technology':['Safety','Tools and Materials','Food and Nutrition','Clothing and Textiles','Woodwork','Metalwork','Electrical Basics','Entrepreneurship','Design and Making','Project Work'],
  'Agricultural Science':['Farm Planning','Soil','Crop Production','Animal Production','Farm Tools','Pests and Diseases','Farm Records','Agribusiness','Post-Harvest Management','Sustainable Agriculture'],
  'Agriculture':['Soils','Crop Husbandry','Animal Husbandry','Farm Management','Farm Economics','Agricultural Extension','Pests and Diseases','Mechanisation','Agribusiness','Sustainable Agriculture'],
  'Applied Technology':['Technology and Society','Materials','Tools','Workshop Safety','Design','Manufacturing','Energy','Electronics','Automation','Project Development'],
  'Art and Design Foundation':['Visual Elements','Drawing','Colour Theory','Composition','Design Principles','Art History','Observation','Creative Thinking','Materials','Portfolio Development'],
  'Art and Design Studio':['Studio Practice','Drawing','Painting','Sculpture','Printmaking','Textiles','Mixed Media','Art Criticism','Contemporary Art','Portfolio Development'],
  'Aviation and Aerospace Engineering':['Aviation Safety','Aircraft Structure','Aerodynamics','Flight Principles','Propulsion','Navigation','Meteorology','Avionics','Maintenance','Aerospace Systems'],
  'Biology':['Cell Biology','Biological Molecules','Nutrition','Transport','Respiration','Photosynthesis','Genetics','Evolution','Ecology','Human Biology'],
  'Biomedical Science':['Cells and Tissues','Anatomy','Physiology','Microbiology','Immunology','Disease','Laboratory Methods','Biochemistry','Genetics','Public Health'],
  'Chemistry':['Atomic Structure','Chemical Bonding','Stoichiometry','Acids Bases and Salts','Redox','Organic Chemistry','Equilibrium','Energetics','Rates of Reaction','Practical Chemistry'],
  'Design Communication Technology':['Technical Drawing','Design Principles','Orthographic Projection','Isometric Drawing','CAD','Materials','Structures','Product Design','Design Evaluation','Design Projects'],
  'Economics':['Basic Economic Concepts','Demand','Supply','Market Equilibrium','Production','National Income','Inflation','Unemployment','Public Finance','Ghanaian Economy'],
  'Engineering':['Engineering Materials','Mechanics','Electrical Principles','Thermodynamics','Fluid Systems','Structures','Manufacturing','Control Systems','Engineering Design','Project Management'],
  'Government':['State and Society','Constitution','Democracy','Political Parties','Pressure Groups','Public Opinion','Elections','Local Government','International Relations','Governance in Ghana'],
  'Geography':['Map Work','Rocks','Weather','Climate','Relief','Population','Settlement','Agriculture','Industry','Environmental Management'],
  'ICT':['Computer Hardware','Software','Operating Systems','Networks','Databases','Spreadsheets','Web Technologies','Cyber Safety','Programming','Information Management'],
  'Literature in English':['Prose','Poetry','Drama','Characterisation','Setting','Theme','Style','Literary Devices','Context','Critical Appreciation'],
  'Manufacturing Engineering':['Manufacturing Processes','Engineering Materials','Workshop Safety','Machining','Fabrication','Production Planning','Quality Control','Automation','Maintenance','Manufacturing Projects'],
  'Performing Arts':['Performance','Drama','Music','Dance','Stagecraft','Voice','Movement','Rehearsal','Audience','Production Project'],
  'Physics':['Measurement','Mechanics','Waves','Heat','Electricity','Magnetism','Light','Atomic Physics','Electronics','Practical Physics'],
  'Robotics':['Robotics Systems','Sensors','Actuators','Control','Programming','Circuits','Mechanical Design','Automation','Robot Ethics','Robotics Projects'],
  'Spanish':['Greetings','Numbers','Family','School','Colours','Days and Months','Food','Directions','Conversation','Grammar'],
  'Accounting':['Accounting Concepts','Double Entry','Ledgers','Trial Balance','Cash Book','Final Accounts','Depreciation','Inventory','Partnership','Analysis of Accounts'],
  'Business Management':['Business Environment','Entrepreneurship','Management','Marketing','Human Resources','Operations','Finance','Business Communication','Ethics','Business Planning'],
  'Business Mathematics':['Percentages','Ratio','Profit and Loss','Simple Interest','Compound Interest','Hire Purchase','Statistics','Matrices','Graphs','Financial Problem Solving'],
  'Home Economics':['Food and Nutrition','Meal Planning','Food Safety','Clothing','Textiles','Family Resource Management','Consumer Education','Child Development','Entrepreneurship','Practical Projects'],
  'Technical':['Technical Drawing','Workshop Safety','Tools','Materials','Mechanics','Electrical Technology','Construction','Manufacturing','Maintenance','Technical Projects']
 };
 const shsOfficial=['Additional Mathematics','Agricultural Science','Agriculture','Applied Technology','Arabic','Art and Design Foundation','Art and Design Studio','Aviation and Aerospace Engineering','Biology','Biomedical Science','Chemistry','Computing','Design Communication Technology','Economics','Engineering','English Language','French','General Science','Government','History','ICT','Literature in English','Manufacturing Engineering','Mathematics','Performing Arts','Physical Education and Health','Physics','Religious and Moral Education','Robotics','Social Studies','Spanish','Geography'];
 function mkTopic(title,subject,level){let d=`${title} is a topic in ${subject}. It focuses on the main ideas, vocabulary, processes, skills and applications learners are expected to understand at ${level}.`;let qs=[];for(let i=1;i<=10;i++)qs.push({question:`${i}. ${i<=3?'Define or describe':'Explain, apply or analyse'} ${title} in a ${level} context.`,answer:d,hint:`Use the definition, features and applications of ${title}.`});return {title,keyIdea:d,explanation:d,examples:Array.from({length:10},(_,i)=>`Practical example ${i+1}: Apply ${title} to a realistic ${subject} situation at ${level}, explain what you did, and state why the result matches the topic.`),questions:qs,quiz:qs,levelStage:level};}
 function ensureSubject(level,subject,topics){if(!C[level])C[level]={};if(!C[level][subject])C[level][subject]=[];let arr=C[level][subject],seen=new Set(arr.map(t=>t.title.toLowerCase()));for(const t of topics){if(!seen.has(t.toLowerCase())){arr.push(mkTopic(t,subject,level));seen.add(t.toLowerCase())}}}
 // Primary curriculum structure published by NaCCA: add History and OWOP across B1-B6; French/Computing are kept at B4-B6 in the 2019 SBC catalogue.
 for(let n=1;n<=6;n++){let l=`Primary ${n}`;if(n<4&&C[l]?.Computing)delete C[l].Computing;ensureSubject(l,'History',packs[l].slice(-8));ensureSubject(l,'Our World Our People',packs[l].slice(0,10));if(n>=4)ensureSubject(l,'French',subjectTopics.French);if(n>=4)ensureSubject(l,'Computing',subjectTopics.Computing);for(const [s,ts] of Object.entries(subjectTopics)){if(C[l]?.[s]&&C[l][s].length<8)ensureSubject(l,s,ts)}}
 for(let n=1;n<=3;n++){let l=`JHS ${n}`;for(const [s,ts] of Object.entries(subjectTopics))if(C[l]?.[s])ensureSubject(l,s,ts)}
 for(let n=1;n<=3;n++){let l=`SHS ${n}`;for(const s of shsOfficial)ensureSubject(l,s,(subjectTopics[s]||packs[l]||['Introduction','Key Concepts','Applications','Practical Work','Assessment Skills']));}
 for(let n=1;n<=3;n++){let l=`SHS ${n}`;const keep=new Set(shsOfficial);Object.keys(C[l]||{}).forEach(s=>{if(!keep.has(s))delete C[l][s]})}
 window.LEARNOVA_CURRICULUM=C;
})();
