const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, ROOT=__dirname, DB=path.join(ROOT,'data.json'), MAX_BODY=1024*1024;
const PROD=process.env.NODE_ENV==='production';
const ALLOW_ORIGIN=process.env.ALLOW_ORIGIN||'*';
const rate=new Map();
const SESSION_TTL=24*60*60*1000;
const sessions=new Map();
function allowed(req){const key=(req.socket.remoteAddress||'unknown')+'|'+req.url;const now=Date.now(), win=60000, max=PROD?120:600;let a=rate.get(key)||[];a=a.filter(t=>now-t<win);if(a.length>=max)return false;a.push(now);rate.set(key,a);return true;}
function load(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return {users:[],school:{classes:[],assignments:[],students:[],teachers:[]}}}}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))} function hash(s){return crypto.createHash('sha256').update(String(s)).digest('hex')} function passwordHash(s){const salt=crypto.randomBytes(16).toString('hex');const dk=crypto.scryptSync(String(s),salt,64).toString('hex');return 'scrypt$'+salt+'$'+dk} function passwordOk(stored,s){if(!stored)return false;if(stored.startsWith('scrypt$')){const [,salt,dk]=stored.split('$');const got=crypto.scryptSync(String(s),salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(dk,'hex'))}return stored===hash(s)}
function json(res,code,obj){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':ALLOW_ORIGIN,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(),geolocation=()','Content-Security-Policy':"default-src 'none'; frame-ancestors 'self';"});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(Buffer.byteLength(b)>MAX_BODY){reject(new Error('Request too large'));req.destroy()}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function userFrom(req){const h=req.headers.authorization||'';const token=h.replace(/^Bearer\s+/i,'');const entry=sessions.get(token);if(!entry)return null;if(Date.now()-entry.created>SESSION_TTL){sessions.delete(token);return null}return entry.user}
async function ai(messages){const url=process.env.AI_BASE_URL||process.env.OPENAI_BASE_URL,key=process.env.AI_API_KEY||process.env.OPENAI_API_KEY,model=process.env.AI_MODEL||'gpt-4o-mini';if(!url||!key)return null;const r=await fetch(url.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},signal:AbortSignal.timeout(12000),body:JSON.stringify({model,messages})});if(!r.ok)throw new Error('AI provider error');const j=await r.json();return j.choices?.[0]?.message?.content||null}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});if(!allowed(req))return json(res,429,{error:'Too many requests'});try{if(req.url==='/robots.txt'){res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-cache'});return res.end('User-agent: *\nAllow: /\n\nSitemap: https://learnova-2wsf.onrender.com/sitemap.xml\n')}if(req.url==='/sitemap.xml'){res.writeHead(200,{'Content-Type':'application/xml; charset=utf-8','Cache-Control':'no-cache'});return fs.createReadStream(path.join(ROOT,'sitemap.xml')).pipe(res)}if(req.url==='/api/health')return json(res,200,{ok:true,service:'Learnova GH Learning Platform + AI',ai:!!(process.env.AI_API_KEY||process.env.OPENAI_API_KEY)});
if(req.url.startsWith('/api/')){const d=load();
 if(req.url==='/api/auth/register'&&req.method==='POST'){const b=await body(req);if(!b.email||!b.password||String(b.password).length<8)return json(res,400,{error:'Email and password required; password must be at least 8 characters'});if(d.users.some(u=>u.email===b.email.toLowerCase()))return json(res,409,{error:'Account already exists'});const u={id:crypto.randomUUID(),name:b.name||'Student',email:b.email.toLowerCase(),password:passwordHash(b.password),role:(PROD?'student':(b.role||'student')),level:b.level||'JHS 2',mastery:{},activity:[]};d.users.push(u);save(d);const token=crypto.randomUUID();sessions.set(token,{user:u,created:Date.now()});return json(res,200,{token,user:{...u,password:undefined}})}
 if(req.url==='/api/auth/login'&&req.method==='POST'){const b=await body(req),u=d.users.find(x=>x.email===String(b.email||'').toLowerCase()&&passwordOk(x.password,b.password||''));if(!u)return json(res,401,{error:'Invalid login'});const token=crypto.randomUUID();sessions.set(token,{user:u,created:Date.now()});return json(res,200,{token,user:{...u,password:undefined}})}
 if(req.url==='/api/me'&&req.method==='GET'){const u=userFrom(req);return u?json(res,200,{user:{...u,password:undefined}}):json(res,401,{error:'Unauthorized'})}
 if(req.url==='/api/sync'&&req.method==='POST'){const u=userFrom(req);if(!u)return json(res,401,{error:'Unauthorized'});const b=await body(req);Object.assign(u,{level:b.level||u.level,mastery:b.mastery||u.mastery,activity:b.activity||u.activity,topics:b.topics||0,quizzes:b.quizzes||0,scoreTotal:b.scoreTotal||0,scoreCount:b.scoreCount||0});const i=d.users.findIndex(x=>x.id===u.id);d.users[i]=u;save(d);return json(res,200,{ok:true})}
 if(req.url==='/api/school'&&req.method==='GET'){const u=userFrom(req);if(!u||!['teacher','admin'].includes(u.role))return json(res,403,{error:'Teacher/Admin only'});return json(res,200,{school:d.school})}
 if(req.url==='/api/school'&&req.method==='POST'){const u=userFrom(req);if(!u||!['teacher','admin'].includes(u.role))return json(res,403,{error:'Teacher/Admin only'});const b=await body(req);d.school=Object.assign(d.school,b.school||{});save(d);return json(res,200,{ok:true,school:d.school})}
 if(req.url==='/api/tutor'&&req.method==='POST'){const u=userFrom(req);const b=await body(req);const l=String(b.level||u?.level||'JHS 2').slice(0,40),s=String(b.subject||'General').slice(0,80),t=String(b.topic||'not selected').slice(0,160);const question=String(b.question||'').trim().slice(0,4000);if(!question)return json(res,400,{error:'Question required'});const system=`You are Learnova AI Tutor 7.0, a patient, accurate school tutor for Ghanaian learners. Student class: ${l}. Subject: ${s}. Topic: ${t}. Answer the student's actual question directly, like a helpful conversational AI tutor. Explain step by step when useful. For Mathematics, show workings. For Science, define terms and explain causes/processes. For languages, include the original-language example and English translation when relevant. Match vocabulary and difficulty to the class. If the question is outside the selected topic but is still a safe school question, answer it directly. Never refuse a valid school question just because the topic field is blank or different. Do not invent curriculum facts; say when something is uncertain. Do not use hints as a substitute for an answer unless the selected mode explicitly asks for hints. Keep the learner engaged with one useful follow-up question when appropriate.`;const messages=[{role:'system',content:system},...(Array.isArray(b.history)?b.history.slice(-10):[]),{role:'user',content:question}];try{const answer=await ai(messages);if(answer)return json(res,200,{answer,source:'ai'});return json(res,200,{answer:null,source:'local'})}catch(e){return json(res,200,{answer:null,source:'local',error:'AI unavailable'})}}
 if(req.url==='/api/ai/coach'&&req.method==='POST'){const u=userFrom(req),b=await body(req);const prompt=`Create a short student study-coach summary. Class: ${b.level||''}. Mastery: ${JSON.stringify(b.mastery||{})}. Mistakes: ${JSON.stringify(b.mistakes||[])}. Give strengths, weak areas and next actions.`;const answer=await ai([{role:'system',content:'You are Learnova AI, a safe patient school learning coach.'},{role:'user',content:prompt}]).catch(()=>null);return json(res,200,{answer})}

 if(req.url==='/api/ai/exam'&&req.method==='POST'){const b=await body(req);const count=Math.min(Number(b.count)||10,40);const prompt=`Create ${count} UNIQUE multiple-choice exam questions for ${b.level||''}, subject ${b.subject||''}, topic ${b.topic||'whole subject'}, difficulty ${b.difficulty||'adaptive'}. The class level must control complexity: Primary uses age-appropriate concrete questions; JHS uses application and reasoning; SHS uses analysis, multi-step reasoning and evaluation. Never repeat or lightly reword a question. Cover different subskills and supplied topics. Return ONLY valid JSON array. Each item must have question, choices (exactly 4 strings), correct (0-based index), answer, hint, topic. Base questions on the supplied curriculum material: ${JSON.stringify(b.questions||[]).slice(0,18000)}`;const raw=await ai([{role:'system',content:'You are Learnova AI Exam Coach. Produce accurate, curriculum-aligned, age-appropriate assessment items. Return JSON only and make every question distinct.'},{role:'user',content:prompt}]).catch(()=>null);let exam=null;if(raw){try{exam=JSON.parse(raw)}catch(e){exam=null}}if(Array.isArray(exam)){const seen=new Set();exam=exam.filter(x=>x&&x.question&&!seen.has(String(x.question).toLowerCase().trim())&&seen.add(String(x.question).toLowerCase().trim())).slice(0,count)}return json(res,200,{exam:Array.isArray(exam)?exam:null,source:exam?'ai':'local'})}
 if(req.url==='/api/ai/practice'&&req.method==='POST'){const b=await body(req);const answer=await ai([{role:'system',content:'You are Learnova AI. Generate age-appropriate school practice. Do not include unsafe or inappropriate material.'},{role:'user',content:`Generate ${b.count||5} practice questions for ${b.level||''}, ${b.subject||''}, topic ${b.topic||''}, difficulty ${b.difficulty||'standard'}. Include answers separately.`}]).catch(()=>null);return json(res,200,{answer})}
 return json(res,404,{error:'API route not found'})}
 let file=req.url==='/'?'/index.html':req.url.split('?')[0];let fp=path.resolve(ROOT,'.'+(file.startsWith('/')?file:'/'+file));if(fp!==ROOT&&!fp.startsWith(ROOT+path.sep))return json(res,403,{error:'Forbidden'});if(!fs.existsSync(fp)||fs.statSync(fp).isDirectory()){fp=path.join(ROOT,'404.html');res.writeHead(404,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(fp).pipe(res)}const ext=path.extname(fp),types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.txt':'text/plain'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(),geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https:; font-src 'self' data:; manifest-src 'self'; worker-src 'self' blob:; media-src 'self' blob:; frame-ancestors 'self'; base-uri 'self'; form-action 'self';",'Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});fs.createReadStream(fp).pipe(res);
}catch(e){console.error(e);json(res,500,{error:'Server error'})}});server.listen(PORT,()=>console.log(`Learnova AI running on http://localhost:${PORT}`));
